AWSTemplateFormatVersion: '2010-09-09'
Description: This template creates an S3 Data bucket for the BFAS data swamp and one for BFAS data lake. It also creates a companion bucket for access logs.
Parameters:
  PROJECT:
    Description: Project name
    Type: String
  ENVIRONMENT:
    Description: Environment
    Type: String
  ETLBUCKET:
    Description: Bucket Name holding ETL code artifacts
    Type: String
  DATASWAMPBUCKET:
    Description: Bucket Name for lake data storage
    Type: String
  
  DATALAKEBUCKET:
    Description: Bucket Name for swamp data storage
    Type: String    
Resources:
  LogsBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: LogDeliveryWrite 
      BucketEncryption: 
        ServerSideEncryptionConfiguration: 
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
  DataSwampBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${DATASWAMPBUCKET}"
      BucketEncryption: 
        ServerSideEncryptionConfiguration: 
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LoggingConfiguration:
        DestinationBucketName: !Sub '${LogsBucket}'
        LogFilePrefix: !Sub 'DataBucketAccessLogs/' 
      Tags:
      - Key: bucketcategory
        Value: "swampbucket"
  DataLakeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${DATALAKEBUCKET}"
      BucketEncryption: 
        ServerSideEncryptionConfiguration: 
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LoggingConfiguration:
        DestinationBucketName: !Sub '${LogsBucket}'
        LogFilePrefix: !Sub 'DataBucketAccessLogs/'
      Tags:
      - Key: bucketcategory
        Value: "lakebucket"
  ETLBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ETLBUCKET}"
      BucketEncryption: 
        ServerSideEncryptionConfiguration: 
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LoggingConfiguration:
        DestinationBucketName: !Sub '${LogsBucket}'
        LogFilePrefix: !Sub 'DataBucketAccessLogs/'
      Tags:
      - Key: bucketcategory
        Value: "etlbucket"       
Outputs:
  DataSwampBucketName:
    Value: !Ref 'DataSwampBucket'
    Description: Name of the S3 Data bucket
    Export:
      Name: !Sub '${AWS::StackName}-DataSwampBucketName'
  DataLakeBucketName:
    Value: !Ref 'DataLakeBucket'
    Description: Name of the S3 Data bucket
    Export:
      Name: !Sub '${AWS::StackName}-DataLakeBucketName'
  ETLBucketName:
    Value: !Ref 'ETLBucket'
    Description: Name of the S3 Data bucket
    Export:
      Name: !Sub '${AWS::StackName}-ETLBucketName'

  LogsBucketName:
    Value: !Ref 'LogsBucket'
    Description: Name of the S3 Logs bucket
    Export:
      Name: !Sub '${AWS::StackName}-LogsBucketName'
  DataSwampBucketArn:
    Value: !GetAtt 'DataSwampBucket.Arn'
    Description: Arn of the S3 Data bucket
    Export:
      Name: !Sub '${AWS::StackName}-DataSwampBucketArn'
  DataLakeBucketArn:
    Value: !GetAtt 'DataLakeBucket.Arn'
    Description: Arn of the S3 Data bucket
    Export:
      Name: !Sub '${AWS::StackName}-DataLakeBucketArn'
  ETLBucketArn:
    Value: !GetAtt 'ETLBucket.Arn'
    Description: Arn of the S3 Data bucket
    Export:
      Name: !Sub '${AWS::StackName}-ETLBucketArn'
  LogsBucketArn:
    Value: !GetAtt 'LogsBucket.Arn'
    Description: Arn of the S3 Logs bucket
    Export:
      Name: !Sub '${AWS::StackName}-LogsBucketArn'
  